### ISSUE TITLE
snipe-it 

### ISSUE THREAD

**Issue by shahima** [shahima/athena#1]
hi  snipe 

i had done my installation now going create licenses can you help me  how to create license 
& csv file format

**Comment by shahima** [comment]
HI Snipe
I installed snipe appllication fine but mail are not come ........when i run task schduler it show asset expire ,license are expire but not sent a mail and it show some error on log i will attach my log as well 
iam using window mechine.
and this are logs
[2016-09-22 10:23:10] production.ERROR: exception 'Swift_TransportException' with message 'Connection to tcp://smtp.gmail.com:587 Timed Out' in C:\xampp\htdocs\snipe-it-2.1.2\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:404
Stack trace:
#0 C:\xampp\htdocs\snipe-it-2.1.2\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_getFullResponse(0)
#1 C:\xampp\htdocs\snipe-it-2.1.2\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting()
#2 C:\xampp\htdocs\snipe-it-2.1.2\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 C:\xampp\htdocs\snipe-it-2.1.2\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(329): Swift_Mailer->send(Object(Swift_Message), Array)
#4 C:\xampp\htdocs\snipe-it-2.1.2\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(151): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 C:\xampp\htdocs\snipe-it-2.1.2\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(214): Illuminate\Mail\Mailer->send('emails.expiring...', Array, Object(Closure))
#6 C:\xampp\htdocs\snipe-it-2.1.2\app\commands\SendExpirationAlerts.php(106): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#7 C:\xampp\htdocs\snipe-it-2.1.2\app\commands\SendExpirationAlerts.php(106): Illuminate\Support\Facades\Mail::send('emails.expiring...', Array, Object(Closure))
#8 C:\xampp\htdocs\snipe-it-2.1.2\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): SendExpirationAlerts->fire()
#9 C:\xampp\htdocs\snipe-it-2.1.2\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\xampp\htdocs\snipe-it-2.1.2\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\xampp\htdocs\snipe-it-2.1.2\vendor\symfony\console\Symfony\Component\Console\Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\snipe-it-2.1.2\vendor\symfony\console\Symfony\Component\Console\Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(SendExpirationAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\snipe-it-2.1.2\vendor\symfony\console\Symfony\Component\Console\Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\snipe-it-2.1.2\artisan(59): Symfony\Component\Console\Application->run()
#15 {main} [] []

**Comment by shahima** [comment]
Hi snipe ,

for above post I forget my mail.php page can you please help us to over come this issue.
Thanks IN advenced
return array(

```
/*
|--------------------------------------------------------------------------
| Mail Driver
|--------------------------------------------------------------------------
|
| Laravel supports both SMTP and PHP's "mail" function as drivers for the
| sending of e-mail. You may specify which one you're using throughout
| your application here. By default, Laravel is setup for SMTP mail.
|
| Supported: "smtp", "mail", "sendmail"
|
*/

'driver' => 'smtp',

/*
|--------------------------------------------------------------------------
| SMTP Host Address
|--------------------------------------------------------------------------
|
| Here you may provide the host address of the SMTP server used by your
| applications. A default option is provided that is compatible with
| the Postmark mail service, which will provide reliable delivery.
|
*/

'host' => 'smtp.mydomain.com',

/*
|--------------------------------------------------------------------------
| SMTP Host Port
|--------------------------------------------------------------------------
|
| This is the SMTP port used by your application to delivery e-mails to
| users of your application. Like the host we have set this value to
| stay compatible with the Postmark e-mail application by default.
|
*/

'port' => 25,

/*
|--------------------------------------------------------------------------
| Global "From" Address
|--------------------------------------------------------------------------
|
| You may wish for all e-mails sent by your application to be sent from
| the same address. Here, you may specify a name and address that is
| used globally for all e-mails that are sent by your application.
|
*/

'from' => array('address' => 'snipe-it@northgateps.com', 'name' => null),

/*
|--------------------------------------------------------------------------
| E-Mail Encryption Protocol
|--------------------------------------------------------------------------
|
| Here you may specify the encryption protocol that should be used when
| the application send e-mail messages. A sensible default using the
| transport layer security protocol should provide great security.
|
*/

'encryption' => 'tls',

/*
|--------------------------------------------------------------------------
| SMTP Server Username
|--------------------------------------------------------------------------
|
| If your SMTP server requires a username for authentication, you should
| set it here. This will get used to authenticate with your server on
| connection. You may also set the "password" value below this one.
|
*/

'username' => null,

/*
|--------------------------------------------------------------------------
| SMTP Server Password
|--------------------------------------------------------------------------
|
| Here you may set the password required by your SMTP server to send out
| messages from your application. This will be given to the server on
| connection so that the application will be able to send messages.
|
*/

'password' => null,

/*
|--------------------------------------------------------------------------
| Sendmail System Path
|--------------------------------------------------------------------------
|
| When using the "sendmail" driver to send e-mails, we will need to know
| the path to where Sendmail lives on this server. A default path has
| been provided here, which will work well on most of your systems.
|
*/

'sendmail' => '/usr/sbin/sendmail -bs',

/*
|--------------------------------------------------------------------------
| Mail "Pretend"
|--------------------------------------------------------------------------
|
| When this option is enabled, e-mail will not actually be sent over the
| web and will instead be written to your application's logs files so
| you may inspect the message. This is great for local development.
|
*/

'pretend' => true,
```

);
